server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /ref-data-service
spring:
  application:
    name: ref-data-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432}/ref_data_service
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432}/ref_data_service
    schemas: public
    user: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}